# Generated by Django 5.1.4 on 2025-03-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('stock', models.IntegerField()),
                ('category', models.CharField(choices=[('Desk', 'میز'), ('Chair', 'صندلی'), ('Safebox', 'صندوق نسوز')], max_length=20)),
            ],
        ),
    ]
